### ISSUE TITLE
Aufgabe 4

### ISSUE THREAD

**Issue by LiudmilaKolesnikova** [sweIhm-ws2018-19/skillproject-do-1#1]
Please, review Aufgabe 4. I'm not sure about the merge node.

**Comment by nicolemjohnson** [comment]
Nicole Johnson will review this
original diagram in wiki page

**Comment by nicolemjohnson** [comment]
Blitzeinstellungen einlesen should go before decision node if flash is on or not. It is the act of the app reading the settings if the flash should be on or not. Need to ask Prof. Frau Socher about the ativity of actually turning the flash on.

**Comment by nicolemjohnson** [comment]
Blitzeinstellungen einlesen and Objekt scharf stellen go either parallel or one after the other. get rid of genug licht mode. Change the Bedingungen in node to outside of node.
