### ISSUE TITLE
Aufgabe 3

### ISSUE THREAD

**Issue by gitmasterMitja** [sweIhm-ws2018-19/skillproject-do-1#6]
Modellieren Sie die folgenden Zusammenhänge in einem UML-Anwendungsfalldiagramm.  Die Nutzer eines Systems zur Vermittlung von Mitfahrgelegenheiten sind Fahrer und Mitfahrer. Fahrer können ihre Fahrten im System eingeben. Fahrten können entweder einfache Fahrten (ein Start- und ein Zielort) oder sogenannte Etappenfahren (ein Startort, mehrere Zwischenziele und ein Zielort) sein. Mitfahrer können nach Mitfahrgelegenheiten suchen. Sowohl das Suchen als auch das Eingeben von Fahrten beinhaltet das Erfassen von Start- oder Zielorten. Außerdem können sowohl Fahrer als auch Mitfahrer Mitfahrgelegenheiten absagen. Weitere Funktionen als hier beschrieben gibt es nicht. Das System ist ein sehr einfaches System. Fahrer und Mitfahrer können nicht über das hier beschriebene System kommunizieren. Die Kontaktaufnahme erfolgt außerhalb des Systems über Telefon oder Messaging Service. Auch die Bezahlung erfolgt außerhalb des Systems. Als Lösungshinweis ist das folgende unvollständige Anwendungsfalldiagramm gegeben. Vervollständigen Sie dieses Diagramm. 
![aufgabe_3_sweim](https://user-images.githubusercontent.com/44065527/47615492-ae1bf580-daaf-11e8-80bc-03e3b612a497.png)

**Comment by nicolemjohnson** [comment]
To be reviewed by Nicole Johnson

**Comment by nicolemjohnson** [comment]
Looks good to me
