### ISSUE TITLE
Aufgabe7

### ISSUE THREAD

**Issue by gitmasterMitja** [sweIhm-ws2018-19/skillproject-do-1#7]
![aufgabe7](https://user-images.githubusercontent.com/44065527/47616012-4cf82000-dab7-11e8-803e-8c57d1b99092.png)

**Comment by LiudmilaKolesnikova** [comment]
Mitja, I'm not sure that we have to use Aggregation. Why did you choose this particular connection?

**Comment by gitmasterMitja** [comment]
Hm i thibk you are right, it should be an association

**Comment by LiudmilaKolesnikova** [comment]
I just don't see the "consists of" or "has" connection here, this "Ganzes - Teil" one. And did you see an example in UMLClassromm book on page 133? I think this is exactly what we have to do.
