### ISSUE TITLE
Aufgabe 9

### ISSUE THREAD

**Issue by gitmasterMitja** [sweIhm-ws2018-19/skillproject-do-1#8]
Erstellen Sie ein Sequenzdiagramm für den Aufruf der Operation „drucken()“ von Dokument1
aus Aufgabe 8.

![aufgabe9](https://user-images.githubusercontent.com/44065527/47618088-2940d400-dacf-11e8-9786-553ea18b3ed2.png)

**Comment by LiudmilaKolesnikova** [comment]
What are dispatch and return in the upper left corner?

**Comment by gitmasterMitja** [comment]
Oops, thats the Standard annotation. I will change that
